### ISSUE TITLE
[Bug] <write the title here>

### ISSUE THREAD

**Issue by toErIpNid** [TeamMFR/MineFantasy-reborn#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

All kinds of the Bewitchment Witch Pants and Robes when worn together make metal armor noises when moving. Another strange thing is it only happens if you wear them together, singular pieces do not do this. 

### Expected behaviour

The items should at most make cloth sounds or none at all.

### Steps to reproduce

Download Bewitchment, download Minefantasy, equip any witch robe and pants, profit. 

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

0.1.5-BETA

### Forge version

1.12.2-14.23.5.2859

### Other mods

![snip](https://user-images.githubusercontent.com/78389307/177044346-8e20c482-aead-4085-b024-c263d2f65a44.PNG)

**Comment by ThatPolishKid99** [comment]
It is interesting that it only happens with some armor pieces and not all, although I think that is intentional, it’s meant to be a weight based thing. 
Regardless, this is a matter of configuration, not exactly a bug
In the item registry config file, you have to define the modded armor pieces to have the proper definition as laid out in that section’s description. By default, all armors that do not have a definition are treated as vanilla armor, I.e, solid hunks of metal.
Feel free to ask questions on the discord if you run into any issues
